# Delete doublons in .bash_history.
export HISTCONTROL=ignoreboth:erasedups

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.
shopt -s histappend

# Per-machine configuration.
if [ -f ~/.bashrc_local ]; then
    source ~/.bashrc_local
fi