# BASH/ZSH Common aliases and functions.
source $HOME/.dotfiles/shell/common
source $HOME/.dotfiles/shell/functions

# Per-machine configuration.
if [ -f ~/.bashrc_local ]; then
    source ~/.bashrc_local
fi

# Needed for some functions (top, etc).
export TERMINFO=/usr/share/terminfo

# zoxide: https://github.com/ajeetdsouza/zoxide.
eval "$(zoxide init bash)"
