# BASH/ZSH Common aliases and functions.
source $HOME/.dotfiles/shell/common
source $HOME/.dotfiles/shell/functions

# Per-machine configuration.
if [ -f ~/.bashrc_local ]; then
    source ~/.bashrc_local
fi

# zoxide: https://github.com/ajeetdsouza/zoxide.
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi
