# Print system information.
if command -v fastfetch &> /dev/null; then
	fastfetch
fi

# Oh My Zsh.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
ZSH_CUSTOM=$HOME/.dotfiles/oh-my-zsh-custom
plugins=(git pyenv)
source $ZSH/oh-my-zsh.sh

# Hide username@hostname.
prompt_context(){}

# BASH/ZSH Common aliases and functions.
source $HOME/.dotfiles/shell/common
source $HOME/.dotfiles/shell/functions

# Per-machine configuration.
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

# fzf: https://github.com/junegunn/fzf.
source <(fzf --zsh)

# zoxide: https://github.com/ajeetdsouza/zoxide.
eval "$(zoxide init zsh)"
