# Oh My Zsh.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
ZSH_CUSTOM=$HOME/.dotfiles/src/oh-my-zsh-custom
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Homebrew.
export PATH="${HOMEBREW_PREFIX}/opt/openssl/bin:$PATH"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:$PATH"

# Pyenv.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Custom scripts.
export PATH="$HOME/.dotfiles/bin:$PATH"

# Per-machine configuration.
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi